(import spork/json)
(import spork/cron)
(import spork/path)
(import spork/tasker)
(import spork/schema)
(import spork/rpc)
(import spork/argparse)
(import spork/test)
(import spork/sh)

(print "spork/json    OK")
(print "spork/cron    OK")
(print "spork/path    OK")
(print "spork/tasker  OK")
(print "spork/schema  OK")
(print "spork/rpc     OK")
(print "spork/argparse OK")
(print "spork/test    OK")
(print "spork/sh      OK")
(print "")
(print "all spork imports OK")
